baseurl      = "https://schapiro.tech"
title        = "Schapiro World"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "A place for my thoughts"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "Schapiro World is a place where I can freely speak my thoughts"
  keywords = "homepage, blog"
  images = [""]

# Socials
[[params.social]]
  name = "github"
  url = "https://github.com/rschapiro"
[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/rasmus-schapiro-8410981b2/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Schapiro World"
    subtitle = "Welcome to Schapiro World"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "schapiro"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"


 # And you can even create generic menu 
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

  [[menu.main]]
    identifier = "goals"
    name       = "Goals"
    url        = "/goals"

  [[menu.main]]
    identifier = "learning plans"
    name       = "Learning Plans"
    url        = "/learning-plans"
  
  [[menu.main]]
    identifier = "learning"
    name       = "My Learning"
    url        = "/my-learning"
  
  [[menu.main]]
    identifier = "reference list"
    name       = "Reference List"
    url        = "/reference-list"
